#!/bin/sh

usage="USAGE
    $0 [--clean] <remote> <branch-prefix>
    push each commit from stdin to its own branch.

OPTIONS
    --clean   delete all branches matching pattern:
              <branch-prefix><hash>

    --dry-run print out the commands to issue, but
              do not run them. has no effect.

EXAMPLE
    > git cherry master | git push-each
    > git branch -r
    origin/gpi-18c4051fc502da15c3c279c37630f6d152ad6b3d
    origin/gpi-22ac071150daf8994f4891d57caeef3b4caf2571
    origin/master

    > git push-each --clean
    > git branch -r
    origin/master"

# defaults
remote="origin"
prefix="gpi-"
clean=0
dryrun=0

while [ $# -gt 0 ]; do
	# get options
	arg="$1"
	case "$arg" in
	--help)
		echo "$usage"
		exit 0 ;;
	--clean)
		clean=1
		shift ;;
	--dry-run)
		dryrun=1
		shift ;;
	--*)
		die "$(eval_gettext "unrecognised option: '\$arg'")" ;;
	*)
		# get args
		case "$#" in
		2)
			remote=$1
			shift
			prefix=$1
			shift ;;
		1)
			remote=$1
			shift ;;
		esac ;;
	esac
done

# clean up mode
if [ $clean -eq 1 ]; then
	spec="($prefix[0-9a-f]{40})"
	for line in $(git branch -r | egrep -wo "$remote/$spec" | egrep -o "$spec")
	do
	echo "git push $remote :$line"
	if [ $dryrun -eq 0 ]; then
		git push "$remote" ":$line"
	fi
	done
	exit 0
fi

# push mode
for line in $(egrep -wo [0-9a-f]{40})
do
	spec="$line:refs/heads/$prefix$line"
	echo "git push $remote $spec"
	if [ $dryrun -eq 0 ]; then
		git push "$remote" "$spec"
	fi
done
