#!/bin/sh

usage() {
	echo "usage: $0 [--clean] <remote> <branch-prefix>"
	echo "push each commit in current branch individually"
	exit 1
}

# defaults
remote="origin"
prefix="gpi-"
mode=""

while [ $# -gt 0 ]; do
	# get options
	arg="$1"
	case "$arg" in
	--clean)
		mode=--clean
		shift ;;
	--*)
		die "$(eval_gettext "unrecognised option: '\$arg'")" ;;
	*)
		# get args
		case "$#" in
		2)
			remote=$1
			shift
			prefix=$1
			shift ;;
		1)
			remote=$1
			shift ;;
		esac ;;
	esac
done

# clean up mode
if test "z$mode" = "z--clean"; then
	spec="($prefix[0-9a-f]{40})"
	for line in $(git branch -r | egrep -wo "$remote/$spec" | egrep -o "$spec")
	do
		git push "$remote" ":$line"
	done
	exit 0
fi

# push mode
for line in $(egrep -wo [0-9a-f]{40})
do
	spec="$line:refs/heads/$prefix$line"
	echo "git push $remote $spec"
	git push "$remote" "$spec"
done
